# Generated by Django 5.0.2 on 2024-02-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="title",
            field=models.CharField(default="default", max_length=100),
        ),
    ]
